# Generated by Django 5.2.3 on 2025-07-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0003_testimonial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
    ]
